/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package papirnyilvantarto;

import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.event.TableModelEvent;

/**
 *
 * @author Darázsi Márk
 */
public class Papirnyilvantarto extends javax.swing.JFrame {

    DB ab;
    
    /**
     * Creates new form Papirnyilvantarto
     */
    public Papirnyilvantarto() {
        initComponents();
        ab = new DB();
        setIcon();
        ab.keszlet_be(tblKeszlet, lekerdez());
        idozito.start();
    }
    
    private String lekerdez() {
        String a = "";
        if (!txtTarhelyKereso.getText().trim().isEmpty())
            a = a + " tarhely LIKE '%" + txtTarhelyKereso.getText().trim() + "%' AND ";
        a = a + " tarhely LIKE '%" + txtTarhelyKereso.getText().trim() + "%' AND ";
        
        String b = "";
        if (!txtMegnevezesKereso.getText().trim().isEmpty())
            b = b + " nev LIKE '%" + txtMegnevezesKereso.getText().trim() + "%' AND ";
        b = b + " nev LIKE '%" + txtMegnevezesKereso.getText().trim() + "%' AND ";
        
        String c = "";
        if (!txtGrammKereso.getText().trim().isEmpty())
            c = c + " gramm LIKE '%" + txtGrammKereso.getText().trim() + "%' AND ";
        c = c + " gramm LIKE '%" + txtGrammKereso.getText().trim() + "%' AND ";
        
        String d = "";
        if (!txtMeretKereso.getText().trim().isEmpty())
            d = d + " meret LIKE '%" + txtMeretKereso.getText().trim() + "%' AND ";
        d = d + " meret LIKE '%" + txtMeretKereso.getText().trim() + "%' AND ";
        
        String e = "";
        if (!txtSzaliranyKereso.getText().trim().isEmpty())
            e = e + " szalirany LIKE '%" + txtSzaliranyKereso.getText().trim() + "%' AND ";
        e = e + " szalirany LIKE '%" + txtSzaliranyKereso.getText().trim() + "%' AND ";
        
        String f = "";
        if (!txtMennyisegKereso.getText().trim().isEmpty())
            f = f + " mennyiseg LIKE '%" + txtMennyisegKereso.getText().trim() + "%' AND ";
        f = f + " mennyiseg LIKE '%" + txtMennyisegKereso.getText().trim() + "%' ";
        
        return "SELECT * FROM leltar WHERE " + a + b + c + d + e + f + " ORDER BY tarhely;";
    }
    
    private void tablabol() {
        int i = tblKeszlet.getSelectedRow();
        if ( i == -1) return;
        Object e = tblKeszlet.getValueAt(i, 0);
        txtTarhely.setText(tblKeszlet.getValueAt(i, 1).toString());
        txtMegnevezes.setText(tblKeszlet.getValueAt(i, 2).toString());
        txtGramm.setText(tblKeszlet.getValueAt(i, 3).toString());
        txtMeret.setText(tblKeszlet.getValueAt(i, 4).toString());
        txtSzalirany.setText(tblKeszlet.getValueAt(i, 5).toString());
        txtMennyiseg.setText(tblKeszlet.getValueAt(i, 6).toString());
    }
    
        private void uj_kijelol() {
        int sordb = tblKeszlet.getRowCount();
        int max = 0;
        int sor = 0;
        for (int i = 0; i < sordb; i++) {
            int n = Integer.parseInt(tblKeszlet.getValueAt(i, 0).toString());
            if (n > max) {
                max = n;
                sor = i;
            }
        }
        tblKeszlet.setRowSelectionInterval(sor, sor);
        tablabol();
    }
    
    private void kijelol(int sorid) {
        int sordb = tblKeszlet.getRowCount();
        for (int i = 0; i < sordb; i++) {
            int id = Integer.parseInt(tblKeszlet.getValueAt(i, 0).toString());
            if (id == sorid) {
                tblKeszlet.setRowSelectionInterval(i, i);
                tablabol();
                break;
            }
        }
    }
    
    private Timer idozito = new Timer(60000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
            ab.keszlet_be(tblKeszlet, lekerdez());
            }
        });
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeszlet = new javax.swing.JTable();
        txtTarhely = new javax.swing.JTextField();
        txtMegnevezes = new javax.swing.JTextField();
        txtGramm = new javax.swing.JTextField();
        txtMeret = new javax.swing.JTextField();
        txtSzalirany = new javax.swing.JTextField();
        txtMennyiseg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnUj = new javax.swing.JButton();
        btnModosit = new javax.swing.JButton();
        txtTarhelyKereso = new javax.swing.JTextField();
        btnSzuresTorles = new javax.swing.JButton();
        btnTorol = new javax.swing.JButton();
        btnMennyisegModosit = new javax.swing.JButton();
        txtGrammKereso = new javax.swing.JTextField();
        txtMeretKereso = new javax.swing.JTextField();
        txtSzaliranyKereso = new javax.swing.JTextField();
        txtMennyisegKereso = new javax.swing.JTextField();
        txtMegnevezesKereso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Papírnyilvántartó");
        setIconImages(null);

        tblKeszlet.setAutoCreateRowSorter(true);
        tblKeszlet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblKeszlet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Tárhely", "Megnevezés", "Grammsúly", "Méret", "Szálirány", "Mennyiség"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKeszlet.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblKeszlet.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblKeszlet.getTableHeader().setReorderingAllowed(false);
        tblKeszlet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblKeszletMouseReleased(evt);
            }
        });
        tblKeszlet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblKeszletKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblKeszlet);
        if (tblKeszlet.getColumnModel().getColumnCount() > 0) {
            tblKeszlet.getColumnModel().getColumn(0).setMinWidth(0);
            tblKeszlet.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblKeszlet.getColumnModel().getColumn(0).setMaxWidth(0);
            tblKeszlet.getColumnModel().getColumn(1).setPreferredWidth(40);
            tblKeszlet.getColumnModel().getColumn(2).setPreferredWidth(80);
            tblKeszlet.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblKeszlet.getColumnModel().getColumn(4).setPreferredWidth(40);
            tblKeszlet.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(txtTarhely);
        jLabel1.setText("Tárhely:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setLabelFor(txtMegnevezes);
        jLabel2.setText("Megnevezés:");
        jLabel2.setToolTipText("");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setLabelFor(txtGramm);
        jLabel3.setText("Gramm:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setLabelFor(txtMeret);
        jLabel4.setText("Méret:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setLabelFor(txtSzalirany);
        jLabel5.setText("Szálirány:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setLabelFor(txtMennyiseg);
        jLabel6.setText("Mennyiség:");

        btnUj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/papirnyilvantarto/uj.png"))); // NOI18N
        btnUj.setText("Új");
        btnUj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjActionPerformed(evt);
            }
        });

        btnModosit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/papirnyilvantarto/modosit.png"))); // NOI18N
        btnModosit.setText("Módosít");
        btnModosit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModositActionPerformed(evt);
            }
        });

        txtTarhelyKereso.setToolTipText("Keresés");
        txtTarhelyKereso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTarhelyKeresoKeyReleased(evt);
            }
        });

        btnSzuresTorles.setBackground(new java.awt.Color(255, 51, 51));
        btnSzuresTorles.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSzuresTorles.setText("Szűrő törlése");
        btnSzuresTorles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSzuresTorlesActionPerformed(evt);
            }
        });

        btnTorol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/papirnyilvantarto/torol.png"))); // NOI18N
        btnTorol.setText("Törlés");
        btnTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTorolActionPerformed(evt);
            }
        });

        btnMennyisegModosit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/papirnyilvantarto/mennyiseg_modosit.png"))); // NOI18N
        btnMennyisegModosit.setText("Mennyiség módosít");
        btnMennyisegModosit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMennyisegModositActionPerformed(evt);
            }
        });

        txtGrammKereso.setToolTipText("Keresés");
        txtGrammKereso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrammKeresoKeyReleased(evt);
            }
        });

        txtMeretKereso.setToolTipText("Keresés");
        txtMeretKereso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMeretKeresoKeyReleased(evt);
            }
        });

        txtSzaliranyKereso.setToolTipText("Keresés");
        txtSzaliranyKereso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSzaliranyKeresoKeyReleased(evt);
            }
        });

        txtMennyisegKereso.setToolTipText("Keresés");
        txtMennyisegKereso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMennyisegKeresoKeyReleased(evt);
            }
        });

        txtMegnevezesKereso.setToolTipText("Keresés");
        txtMegnevezesKereso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMegnevezesKeresoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTarhely)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMegnevezes)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGramm)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMeret)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSzalirany))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMennyiseg)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTarhelyKereso, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMegnevezesKereso, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGrammKereso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMeretKereso, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSzaliranyKereso, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMennyisegKereso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnModosit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSzuresTorles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTorol)))
                    .addComponent(btnMennyisegModosit, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMennyisegModosit, btnModosit, btnSzuresTorles, btnTorol, btnUj});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSzuresTorles, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTarhelyKereso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGrammKereso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMeretKereso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSzaliranyKereso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMegnevezesKereso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMennyisegKereso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMennyisegModosit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTorol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModosit)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTarhely, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMegnevezes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtGramm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSzalirany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMennyiseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMennyisegModosit, btnModosit, btnSzuresTorles, btnTorol, btnUj, txtMennyisegKereso});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSzuresTorlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSzuresTorlesActionPerformed
        txtTarhelyKereso.setText("");
        txtMegnevezesKereso.setText("");
        txtGrammKereso.setText("");
        txtMeretKereso.setText("");
        txtSzaliranyKereso.setText("");
        txtMennyisegKereso.setText("");
        ab.keszlet_be(tblKeszlet, lekerdez());
    }//GEN-LAST:event_btnSzuresTorlesActionPerformed

    private void tblKeszletMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKeszletMouseReleased
        tablabol();
    }//GEN-LAST:event_tblKeszletMouseReleased

    private void tblKeszletKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKeszletKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP
            || evt.getKeyCode() == KeyEvent.VK_DOWN
            || evt.getKeyCode() == KeyEvent.VK_PAGE_UP
            || evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN)
            tablabol();
    }//GEN-LAST:event_tblKeszletKeyReleased

    private void btnUjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjActionPerformed
        int n = ab.hozzaad(txtTarhely.getText(),
                           txtMegnevezes.getText(),
                           txtGramm.getText(),
                           txtMeret.getText(),
                           txtSzalirany.getText(),
                           txtMennyiseg.getText());
        if (n > 0) {
            ab.keszlet_be(tblKeszlet, lekerdez());
            uj_kijelol();
            txtTarhely.requestFocus();
            txtTarhely.selectAll();
        }
    }//GEN-LAST:event_btnUjActionPerformed

    private void btnTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTorolActionPerformed
        int i = tblKeszlet.getSelectedRow();
        if (i == -1) return;
        ab.torol(Integer.parseInt(tblKeszlet.getValueAt(i, 0).toString()));
        ab.keszlet_be(tblKeszlet, lekerdez());
    }//GEN-LAST:event_btnTorolActionPerformed

    private void btnModositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModositActionPerformed
        int i = tblKeszlet.getSelectedRow();
        if (i == -1) return;
        int sorid = Integer.parseInt(tblKeszlet.getValueAt(i, 0).toString());
        int n = ab.modosit(sorid, txtTarhely.getText(),
                           txtMegnevezes.getText(), txtGramm.getText(),
                           txtMeret.getText(), txtSzalirany.getText(),
                           txtMennyiseg.getText());
        if (n>0) {
            ab.keszlet_be(tblKeszlet, lekerdez());
            kijelol(sorid);
        }
    }//GEN-LAST:event_btnModositActionPerformed
    
    private void btnMennyisegModositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMennyisegModositActionPerformed
        int i = tblKeszlet.getSelectedRow();
        if (i == -1) return;
        int sorid = Integer.parseInt(tblKeszlet.getValueAt(i, 0).toString());
        int n = ab.mennyiseg_modosit(sorid, txtMennyiseg.getText());
        if (n>0) {
            ab.keszlet_be(tblKeszlet, lekerdez());
            kijelol(sorid);
        }
    }//GEN-LAST:event_btnMennyisegModositActionPerformed

    private void txtTarhelyKeresoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTarhelyKeresoKeyReleased
        ab.keszlet_be(tblKeszlet, lekerdez());
    }//GEN-LAST:event_txtTarhelyKeresoKeyReleased

    private void txtGrammKeresoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrammKeresoKeyReleased
        ab.keszlet_be(tblKeszlet, lekerdez());
    }//GEN-LAST:event_txtGrammKeresoKeyReleased

    private void txtMeretKeresoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMeretKeresoKeyReleased
        ab.keszlet_be(tblKeszlet, lekerdez());
    }//GEN-LAST:event_txtMeretKeresoKeyReleased

    private void txtSzaliranyKeresoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSzaliranyKeresoKeyReleased
        ab.keszlet_be(tblKeszlet, lekerdez());
    }//GEN-LAST:event_txtSzaliranyKeresoKeyReleased

    private void txtMennyisegKeresoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMennyisegKeresoKeyReleased
        ab.keszlet_be(tblKeszlet, lekerdez());
    }//GEN-LAST:event_txtMennyisegKeresoKeyReleased

    private void txtMegnevezesKeresoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMegnevezesKeresoKeyReleased
        ab.keszlet_be(tblKeszlet, lekerdez());
    }//GEN-LAST:event_txtMegnevezesKeresoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Papirnyilvantarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Papirnyilvantarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Papirnyilvantarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Papirnyilvantarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Papirnyilvantarto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMennyisegModosit;
    private javax.swing.JButton btnModosit;
    private javax.swing.JButton btnSzuresTorles;
    private javax.swing.JButton btnTorol;
    private javax.swing.JButton btnUj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKeszlet;
    private javax.swing.JTextField txtGramm;
    private javax.swing.JTextField txtGrammKereso;
    private javax.swing.JTextField txtMegnevezes;
    private javax.swing.JTextField txtMegnevezesKereso;
    private javax.swing.JTextField txtMennyiseg;
    private javax.swing.JTextField txtMennyisegKereso;
    private javax.swing.JTextField txtMeret;
    private javax.swing.JTextField txtMeretKereso;
    private javax.swing.JTextField txtSzalirany;
    private javax.swing.JTextField txtSzaliranyKereso;
    private javax.swing.JTextField txtTarhely;
    private javax.swing.JTextField txtTarhelyKereso;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("programikon.png")));
    }
}
